"""add diaries

Revision ID: 70b1ce5360c8
Revises: 4eba29c29e66
Create Date: 2026-06-29 16:19:35.365585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b1ce5360c8'
down_revision: Union[str, Sequence[str], None] = '4eba29c29e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('content', sa.String(length=280), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diaries_day'), ['day'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diaries_day'))

    op.drop_table('diaries')
    # ### end Alembic commands ###
